include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - android/**
    - ios/**
    - web/**
    - linux/**
    - macos/**
    - windows/**
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Keep defaults; tweak only if needed
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_print: true
